language: python
python:
  - "2.7"
  - "3.4"
env:
  - NODE_VERSION="10.7"

before_install:
  - nvm install $NODE_VERSION

install:
  - npm install -g ajv-cli
  - pip install -r requirements.txt

script:
  - ./scripts/lint-json-dirs
  - pytest
  - ajv compile -s schemas/tool.json
  - ajv compile -s schemas/business_rule.json
