language: python
python:
  - "2.7"
  - "3.4"
env:
  - NODE_VERSION="10.7"

before_install:
  - nvm install $NODE_VERSION

install:
  - npm install -g ajv-cli
  - pip install -r requirements.txt

script:
  - ./scripts/lint-json-dirs
  - pytest
  - ajv compile -s schemas/types.json
  - ajv compile -s schemas/tool.json
  - ajv compile -s schemas/par_property.json
  - ajv compile -s schemas/preservation_action_type.json
  - ajv compile -s schemas/format.json -r schemas/types.json
  - ajv compile -s schemas/preservation_action.json -r schemas/types.json -r schemas/preservation_action_type.json -r schemas/par_property.json -r schemas/tool.json
  - ajv compile -s schemas/business_rule.json -r schemas/types.json -r schemas/preservation_action_type.json -r schemas/preservation_action.json -r schemas/par_property.json -r schemas/tool.json
